name: GNU Make core forking for GitHub Actions

on:
  push:
    branches:
      - 4.4.1

permissions:
  contents: write
  pull-requests: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Obtain source code from ftp.gnu.org
        run: |
          wget https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz -O make-4.4.1.tar.gz

      - name: Install Zstandard for Extraction
        run: sudo apt install -y xz-utils tar

      - name: Extract Source Code into Root Directory
        run: tar --strip-components=1 -xf make-4.4.1.tar.gz

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          rm make-4.4.1.tar.gz
          git add .
          git commit -m "GNU Make core forking for GitHub Actions, version 4.4.1"
          git push
